openapi: 3.0.0
info:
  title: Farmacia API
  description: API para gerenciamento de produtos da farmácia
  version: 1.0.0
  contact:
    name: Suporte
    email: suporte@farmacia.com

servers:
  - url: http://localhost:8000/api
    description: Servidor local de desenvolvimento

tags:
  - name: Products
    description: Operações relacionadas a produtos

paths:
  /products:
    get:
      tags:
        - Products
      summary: Listar produtos
      description: Retorna uma lista paginada de produtos com opções de filtro
      parameters:
        - name: category
          in: query
          description: Filtrar por categoria
          required: false
          schema:
            type: string
        - name: min_price
          in: query
          description: Preço mínimo
          required: false
          schema:
            type: number
            format: float
        - name: max_price
          in: query
          description: Preço máximo
          required: false
          schema:
            type: number
            format: float
        - name: perPage
          in: query
          description: Número de itens por página
          required: false
          schema:
            type: integer
            default: 8
      responses:
        '200':
          description: Lista de produtos retornada com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductPagination'

    post:
      tags:
        - Products
      summary: Criar novo produto
      description: Cria um novo produto no sistema
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductInput'
      responses:
        '201':
          description: Produto criado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'

  /products/{id}:
    get:
      tags:
        - Products
      summary: Obter produto por ID
      description: Retorna os detalhes de um produto específico
      parameters:
        - name: id
          in: path
          required: true
          description: ID do produto
          schema:
            type: integer
      responses:
        '200':
          description: Produto encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '404':
          description: Produto não encontrado

    put:
      tags:
        - Products
      summary: Atualizar produto
      description: Atualiza os dados de um produto existente
      parameters:
        - name: id
          in: path
          required: true
          description: ID do produto
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductInput'
      responses:
        '200':
          description: Produto atualizado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '404':
          description: Produto não encontrado

    delete:
      tags:
        - Products
      summary: Deletar produto
      description: Remove um produto do sistema
      parameters:
        - name: id
          in: path
          required: true
          description: ID do produto
          schema:
            type: integer
      responses:
        '200':
          description: Produto deletado com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Produto deletado com sucesso."
        '404':
          description: Produto não encontrado

components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: integer
          description: ID único do produto
        name:
          type: string
          description: Nome do produto
        price:
          type: number
          format: float
          description: Preço do produto
        description:
          type: string
          description: Descrição do produto
        category:
          type: string
          description: Categoria do produto
        img:
          type: string
          description: URL da imagem do produto
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    ProductInput:
      type: object
      required:
        - name
        - price
        - category
      properties:
        name:
          type: string
          description: Nome do produto
          maxLength: 255
        price:
          type: number
          format: float
          description: Preço do produto
          minimum: 0
        description:
          type: string
          description: Descrição do produto
        category:
          type: string
          description: Categoria do produto
          maxLength: 255
        img:
          type: string
          description: URL da imagem do produto

    ProductPagination:
      type: object
      properties:
        current_page:
          type: integer
        data:
          type: array
          items:
            $ref: '#/components/schemas/Product'
        first_page_url:
          type: string
        from:
          type: integer
        last_page:
          type: integer
        last_page_url:
          type: string
        links:
          type: array
          items:
            type: object
            properties:
              url:
                type: string
              label:
                type: string
              active:
                type: boolean
        next_page_url:
          type: string
        path:
          type: string
        per_page:
          type: integer
        prev_page_url:
          type: string
        to:
          type: integer
        total:
          type: integer
